id: 15b6d4c0c12f446284d366ebeb67bfaf
initial_creation_type: ocr
source_metadata:
  volumes:
    285813ac983f4e1a94896346c6db1a88:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
